version: "3.5"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    ports:
      - '5432:5432'
    volumes: 
      - ~/example/postgres/:/var/lib/postgresql/data
  golang-restapi: # The name of the service
    build:
      context: ..
      dockerfile: deploy/Dockerfile # Location of our Dockerfile
    image: despenrado/golang-restapi-webmesk:test.0.1
    container_name: golang-restapi-webmesk # Container name
    depends_on: # start after
      - db
    ports:
      - "8081:8081"
    links: # list mapping: service_name:name_how_will_see_your_program
      - "db:psql"