postgresql:
  master:
    host: psql
    port: 5432
    user: gorm
    password: gorm
    dbname: webmesk
    sslmode:  disable
    timeZone: Europe/Warsaw
    autoMigration: true
  slave:
    # - host: psql-slave-1
    #   port: 5432
    # - host: psql-slave-2
    #   port: 5432
rest_api_server:
  port: 8081
jwt:
  token_expires: 31536000s
  jwt_key: test_key
redis:
  addr: redis:6379